import { ICard } from './types';

// const original: ICard[] = [
//   {
//     id: '1',
//     name: 'barrel',
//     value: 'queen',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: 'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
//   },
//   {
//     id: '2',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: 'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
//   },
//   {
//     id: '3',
//     name: 'dynamite',
//     value: 'two',
//     suit: 'hearts',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '5',
//     name: 'jail',
//     value: 'jack',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '6',
//     name: 'jail',
//     value: 'ten',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '7',
//     name: 'jail',
//     value: 'four',
//     suit: 'hearts',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '8',
//     name: 'mustang',
//     value: 'eight',
//     suit: 'hearts',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '9',
//     name: 'mustang',
//     value: 'nine',
//     suit: 'hearts',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '10',
//     name: 'remington',
//     value: 'king',
//     suit: 'clubs',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '11',
//     name: 'rev carabine',
//     value: 'ace',
//     suit: 'clubs',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '12',
//     name: 'schofield',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '13',
//     name: 'schofield',
//     value: 'jack',
//     suit: 'clubs',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '14',
//     name: 'schofield',
//     value: 'queen',
//     suit: 'clubs',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '15',
//     name: 'scope',
//     value: 'ace',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '16',
//     name: 'volcanic',
//     value: 'ten',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '17',
//     name: 'volcanic',
//     value: 'ten',
//     suit: 'clubs',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '18',
//     name: 'winchester',
//     value: 'eight',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '19',
//     name: 'bang',
//     value: 'ace',
//     suit: 'spades',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '20',
//     name: 'bang',
//     value: 'two',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '21',
//     name: 'bang',
//     value: 'three',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '22',
//     name: 'bang',
//     value: 'four',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '23',
//     name: 'bang',
//     value: 'five',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '24',
//     name: 'bang',
//     value: 'six',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '25',
//     name: 'bang',
//     value: 'seven',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '26',
//     name: 'bang',
//     value: 'eight',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '27',
//     name: 'bang',
//     value: 'nine',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '28',
//     name: 'bang',
//     value: 'ten',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '29',
//     name: 'bang',
//     value: 'jack',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '30',
//     name: 'bang',
//     value: 'queen',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '31',
//     name: 'bang',
//     value: 'king',
//     suit: 'diamond',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '32',
//     name: 'bang',
//     value: 'ace',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '33',
//     name: 'bang',
//     value: 'two',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '34',
//     name: 'bang',
//     value: 'three',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '35',
//     name: 'bang',
//     value: 'four',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '36',
//     name: 'bang',
//     value: 'five',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '37',
//     name: 'bang',
//     value: 'six',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '38',
//     name: 'bang',
//     value: 'seven',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '39',
//     name: 'bang',
//     value: 'eight',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '40',
//     name: 'bang',
//     value: 'nine',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '41',
//     name: 'bang',
//     value: 'ten',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '42',
//     name: 'bang',
//     value: 'jack',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '43',
//     name: 'bang',
//     value: 'queen',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '44',
//     name: 'bang',
//     value: 'king',
//     suit: 'clubs',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '32',
//     name: 'bang',
//     value: 'ace',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '33',
//     name: 'bang',
//     value: 'two',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '34',
//     name: 'bang',
//     value: 'three',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '35',
//     name: 'bang',
//     value: 'four',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '36',
//     name: 'bang',
//     value: 'five',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '37',
//     name: 'bang',
//     value: 'six',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '38',
//     name: 'bang',
//     value: 'seven',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '39',
//     name: 'bang',
//     value: 'eight',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '40',
//     name: 'bang',
//     value: 'nine',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '41',
//     name: 'bang',
//     value: 'ten',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '42',
//     name: 'bang',
//     value: 'jack',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '43',
//     name: 'bang',
//     value: 'queen',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '44',
//     name: 'bang',
//     value: 'king',
//     suit: 'hearts',
//     type: 'action',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
//   {
//     id: '3',
//     name: 'barrel',
//     value: 'king',
//     suit: 'spades',
//     type: 'equipment',
//     imageUrl: '',
//   },
// ];

const original: ICard[] = [];

export default [...original];
