import { ICard } from '../game/types';

const cardsOriginal: ICard[] = [
  {
    id: 'rhSMooJXreHwPvs8U9b_U',
    value: 12,
    name: 'barrel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'Zt7UMNPofdRQx91nTBjZ9',
    value: 13,
    name: 'barrel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'VilYqLA9AsQaym-Hj2SW4',
    value: 2,
    name: 'dynamite',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/dynamite_gq525m.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '5hvBU6xsqn0nyPJ89azdU',
    value: 4,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '31HqKJYeqWkf8DPzo0BmM',
    value: 10,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '-ol5SGNDrqDVzHhaglr_J',
    value: 11,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'o-xocVC9VTlqhBG4MHbB-',
    value: 8,
    name: 'mustang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mustang_pht7ms.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'FVxPmCPfo4fKYOJ_Hd0Fn',
    value: 9,
    name: 'mustang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mustang_pht7ms.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'RipwgLqZPd7wPaAHgSmpN',
    value: 13,
    name: 'remington',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/remington_dtsgzi.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'gT16xB_lzBUxUBl5F7GWB',
    value: 14,
    name: 'rev carabine',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/carabine_czyogt.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'drpZ99muNlcKuKLU0WUg_',
    value: 11,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '5vav0WFjWY8MF4x0cvSKM',
    value: 12,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'stm7jk3gxPM8OkLW-j7H_',
    value: 13,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'wiKIVcHiUVPsDyB_Ux2fu',
    value: 14,
    name: 'scope',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mirino_gbne0b.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'W4JzkaQFJcPfN2zeelgaw',
    value: 10,
    name: 'volcanic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/volcanic_dwrloi.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'EDDb4QeyOZKDFUhc_g8SX',
    value: 10,
    name: 'volcanic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/volcanic_dwrloi.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '_-aAC77duLeAYx-go__IQ',
    value: 8,
    name: 'winchester',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/winchester_sy1r19.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'yatRYVXm7KAlOTIz377E1',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'RdJnA0SIOTvSxTOCOXGnv',
    value: 2,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'U0VIULrFuE67EN-UoxAGE',
    value: 3,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'QZZ8vsZEiqKDX_0QUlKwG',
    value: 4,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '-tvISdw4NhvU3FOpdL0Vz',
    value: 5,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'aKiol5FSorSHdRryeVqmC',
    value: 6,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'ciORa6mmE7iqWQsCznifB',
    value: 7,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'wrAfgdtGxA2nA0xz3MPKR',
    value: 8,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Z6-izVSCiM6nZxYH-VfFt',
    value: 9,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Z25VVBv1Xsh-DenDVy_-i',
    value: 10,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Qh2Z_vFrUc-X2ykBpdAqi',
    value: 11,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '3-KPqEw-1DHj8rxslWErI',
    value: 12,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Tu4zT2xshZVkN8NXZp4eO',
    value: 13,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'GZJQQSHuAEJr2LVIZmtxC',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '4ZM_8tApWN3JM8aOo1RMK',
    value: 12,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'IafqKETKKi10fnDiOsiW6',
    value: 13,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '8VcK6behOeu_i5v9rHLny',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'YMSydDFzDWO2IHeM8eTJ_',
    value: 2,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Ip53iSuaG-CpD_jAgbOI9',
    value: 3,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'aUAYA8BDt8dRIi8mwpg-l',
    value: 4,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'M2AJYGqsVhR3skGVY-Whk',
    value: 5,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'HI_rI_SU3QgzLZS1Yr6vb',
    value: 6,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'z5GMCxALxC2YRLYz5T3R1',
    value: 7,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'BY-fLgfCVm9WsIxfndwg9',
    value: 8,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '8ygMPu5ZU94G8OXFvIcrU',
    value: 9,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'R9JWhrhRQBI1hfkjqE4yM',
    value: 6,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'y15J765JDDK_i0bqwUU90',
    value: 7,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'hsmoBBXqDxuxlDtGXKAsx',
    value: 8,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'C7ZPoHkV2WbKzQY_tfwuY',
    value: 9,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'W2-Yoi_uIWGMEZ3EmTohM',
    value: 10,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'jAAxJmhcmhLuLY0mjcBdl',
    value: 11,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'wmLKLRyE8mj5y8NyrEIlO',
    value: 13,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '454JJFe0lu_KGrHlTJqR_',
    value: 9,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '2XpSUS1Np3oF4FH6pIM5o',
    value: 10,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'zhth5fsp628DfLKvSrAd6',
    value: 11,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'WTHIUpxcB5scklQDhh98H',
    value: 8,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '8swMRyb53Y7H1ESjDAQVY',
    value: 12,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 't4WCFXT3Agy0csOLuvij4',
    value: 11,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'SumZq4lsRCOHQ69HUbimD',
    value: 10,
    name: 'gatling',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/gatling_vxac7t.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'SRbrIkg9Sc4vcSxfDI3LJ',
    value: 9,
    name: 'general store',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/emporio_ldjfxn.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'aFd7p-zAMNyHHN59cCF2j',
    value: 12,
    name: 'general store',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/emporio_ldjfxn.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'wrnzievJVX_P7s-gVO8BC',
    value: 13,
    name: 'indians',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/indiani_mlfftz.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'i1Lb999GxJ4cnFp60Fd4S',
    value: 14,
    name: 'indians',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/indiani_mlfftz.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'D96z7Ug64csBFSwOcrJAf',
    value: 10,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'TxKie_zatNEHeai9wMF0H',
    value: 11,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'kwqaAKWRtVF2bZFFX-m5b',
    value: 12,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'PAZV9NoPL-gcOFeoUOLUr',
    value: 13,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'VAbi_JY7PDwGPQM5Tv5Co',
    value: 14,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'Fe25MR-1k7qVjRUfwMrB4',
    value: 2,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'zS4To8Msw0iP41oM93MGu',
    value: 3,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '0Y87LF3J-nyBVqGS1Vjht',
    value: 4,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'cQEoBaEnl2bQmgkgZTVdF',
    value: 5,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'fkCeec5GqQgQzwuRlYUjm',
    value: 6,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'dnKjZF_bOHfL-mh04SviX',
    value: 7,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'VbsfV4gubdXleMoIPonUw',
    value: 8,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'LPiPCjm9Zmalo2xef8p1g',
    value: 11,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'JPDllU2Tzmda48pSuN6nH',
    value: 12,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'iZNWQuwmgtLl2Y4UO6Uxs',
    value: 13,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'qGLRAI7lrF0LNU2u2m9ne',
    value: 8,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'lEj5P0dJNwbnPkRHHOZ0-',
    value: 5,
    name: 'saloon',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/saloon_oubya5.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'PIkh0-vSQloPj7p8qeMta',
    value: 8,
    name: 'stagecoach',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/diligenza_wpu1kg.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '3vwOMxVOKlE_2cE9NkZv1',
    value: 9,
    name: 'stagecoach',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/diligenza_wpu1kg.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'nGfKimmZ_z_9FJVfT8ztz',
    value: 3,
    name: 'wells fargo',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/wellsfargo_zfpfjj.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
];

export const cards = [...cardsOriginal];
