import { ICard } from '../original';

export const cards_VOS: ICard[] = [
  {
    id: 'hnuFz3JAzS7IVGcQry_Ms',
    value: 9,
    name: 'bounty',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_taglia_fqzwvn.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: '_N9kHJ4Di1wYREcFokCAr',
    value: 9,
    name: 'ghost',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888440/bang/valley%20of%20shadows/07_fantasma_vbgxxt.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'ivFYr5MmvqgB1JgDfiGjN',
    value: 10,
    name: 'ghost',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888440/bang/valley%20of%20shadows/07_fantasma_vbgxxt.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'mSP-QyH5NnbqZE9dyofqI',
    value: 4,
    name: 'lemat',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_lemat_fmlaxe.png',
    suit: 'diamond',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: 'QRqRoOuSKOb4vUvNvaNOv',
    value: 7,
    name: 'rattlesnake',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_serpenteasonagli_hzqbw9.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'yyVdKRf1Z-mOw5Xy-hbyE',
    value: 13,
    name: 'shotgun',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_shotgun_egcipc.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: '5Xjazpb-V1VOA4pKuOSiV',
    value: 6,
    name: 'aim',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_mira_mwmfi5.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
    playWithBang: true,
  },
  {
    id: 'h5cQmnL12FsEcP2hatLt3',
    value: 12,
    name: 'backfire',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_ritornodifiamma_sjiyga.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'Dlv1a5AcSHPjkCs7XplWW',
    value: 12,
    name: 'bandidos',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_bandidos_tn7pge.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: 'vEpCP4TU_FjZfkJD_8roz',
    value: 3,
    name: 'escape',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_fuga_jca9rd.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: 'MUVfzdCrRiSQgO-2YA5wl',
    value: 2,
    name: 'fanning',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_sventagliata_be5tbq.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'Oy7IKmW_I4XnCpinzH6a_',
    value: 8,
    name: 'last call',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_ultimogiro_njn4jx.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: 'y8cECGP71M6E3m5CrBUQr',
    value: 11,
    name: 'poker',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_poker_crcfaq.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
    playWithBang: false,
  },
  {
    id: 'q5WsOt1CoBV9yLY9BwMrh',
    value: 5,
    name: 'saved',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888441/bang/valley%20of%20shadows/07_salvo_ee8b1m.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'SZkBGJsBNpE8wsAe_yOG9',
    value: 14,
    name: 'tomahawk',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_tomahawk_vz2nzo.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
    playWithBang: false,
  },
  {
    id: 'e7QclgTYg2vIu9vKfiVf8',
    value: 14,
    name: 'tornado',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1606888442/bang/valley%20of%20shadows/07_tornado_g2xesa.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
    playWithBang: false,
  },
];
