export type CardNameVOS =
  | 'tornado'
  | 'last call'
  | 'fanning'
  | 'tomahawk'
  | 'aim'
  | 'backfire'
  | 'poker'
  | 'saved'
  | 'escape'
  | 'bandidos'
  | 'bounty'
  | 'shotgun'
  | 'rattlesnake'
  | 'lemat'
  | 'ghost';

export type CardNameDodgeCity =
  | 'binocular'
  | 'hideout'
  | 'brawl'
  | 'dodge'
  | 'punch'
  | 'rag time'
  | 'springfield'
  | 'tequila'
  | 'whisky'
  | 'bible'
  | 'buffalo rifle'
  | 'can can'
  | 'canteen'
  | 'conestoga'
  | 'derringer'
  | 'howitzer'
  | 'iron plate'
  | 'knife'
  | 'pepperbox'
  | 'pony express'
  | 'sombrero'
  | 'ten gallon hat';

export type CardNameExpansion = CardNameVOS | CardNameDodgeCity;
