import { ICard } from '../game/types';

export const cardsOriginal: ICard[] = [
  {
    id: 'NW_LoCMtQ',
    value: 12,
    name: 'barrel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'z52aLWZYPH',
    value: 13,
    name: 'barrel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/barile_z8ibbs.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '8hmUTKeP-G',
    value: 2,
    name: 'dynamite',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/dynamite_gq525m.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '9iIFRA1oCB',
    value: 4,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'kFLRzk0u2A',
    value: 10,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '0lcnjkGNdQ',
    value: 11,
    name: 'jail',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/prigione_k3bbei.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '5mN0myOMr8',
    value: 8,
    name: 'mustang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mustang_pht7ms.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'mI2rVgVpht',
    value: 9,
    name: 'mustang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mustang_pht7ms.png',
    suit: 'hearts',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'sXUx7yXM3m',
    value: 13,
    name: 'remington',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/remington_dtsgzi.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'd4dt2cUeF0',
    value: 14,
    name: 'rev carabine',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/carabine_czyogt.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'Sbve6-omUt',
    value: 11,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'yDL_FPV1g5',
    value: 12,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'n34Tl-5oDr',
    value: 13,
    name: 'schofield',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/schofield_clag8z.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'TSilVLZ-UV',
    value: 14,
    name: 'scope',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mirino_gbne0b.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'Fxx7eqqFCm',
    value: 10,
    name: 'volcanic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/volcanic_dwrloi.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: '2xikjsyVZs',
    value: 10,
    name: 'volcanic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/volcanic_dwrloi.png',
    suit: 'clubs',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'VLB7Ii087-_',
    value: 8,
    name: 'winchester',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/winchester_sy1r19.png',
    suit: 'spades',
    type: 'equipment',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'P2a7-3m63NW',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'UCISqzrlh7m',
    value: 2,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'J3KjwH_vFvT',
    value: 3,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'wPeT0piteaz',
    value: 4,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'dxuH5AzsYw-',
    value: 5,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'EagSS8uliUi',
    value: 6,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'ukJc1INQovK',
    value: 7,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'rJpAk_ldt4O',
    value: 8,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'WfJdFRqh8v1',
    value: 9,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'RybQbYIlfwW',
    value: 10,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'ux_9TyM4gPm',
    value: 11,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '8mT1RTyZEx0',
    value: 12,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '559xYoIaa6J',
    value: 13,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'aq2n_RYXrbJ',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Mhs_BtmxQnz',
    value: 12,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'qEoZwFB3JOv',
    value: 13,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'LDWFsDIaVP6',
    value: 14,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'FS1x_i4I7sf',
    value: 2,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'o30DHsx85PZ',
    value: 3,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'k02zPBPLXX0',
    value: 4,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'f0NEYuq3sIQ',
    value: 5,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'ri361zAPWBX',
    value: 6,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'Sprz2XLVRgH',
    value: 7,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'vCp3HDm2KCN',
    value: 8,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'FIdS8scgNUz',
    value: 9,
    name: 'bang',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/bang_elk9mw.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'LRTJGFUEMIR',
    value: 6,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'mlqAYRROWTC',
    value: 7,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'PupGGWkRHKt',
    value: 8,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'rHNhiXIrWqj',
    value: 9,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'FqUyl-UjjZ4',
    value: 10,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'nv4sPpBm4x1',
    value: 11,
    name: 'beer',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/birra_hjgptv.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'OP8UlqFPOhI',
    value: 13,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'lT-WqWaXhP_',
    value: 9,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'n_db-dwNxsq',
    value: 10,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: '4_rWK2wxodo',
    value: 11,
    name: 'cat balou',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/catbalou_fihyoi.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'zi5OpfKonpv',
    value: 8,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'yUO_e1Yg8VB',
    value: 12,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: '368Lg1-bpNn',
    value: 11,
    name: 'duel',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/duello_ipnsk5.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: true,
  },
  {
    id: 'k3Gax9IRj4d',
    value: 10,
    name: 'gatling',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/gatling_vxac7t.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 't0XIve0oHGd',
    value: 9,
    name: 'general store',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/emporio_ldjfxn.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: '48j924lBaID',
    value: 12,
    name: 'general store',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/emporio_ldjfxn.png',
    suit: 'spades',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'sR8ita4S5iQ',
    value: 13,
    name: 'indians',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/indiani_mlfftz.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: 'q3MxBwfa-m7',
    value: 14,
    name: 'indians',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/indiani_mlfftz.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: true,
    isTargeted: false,
  },
  {
    id: '6MD26Ex4eqm',
    value: 10,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'mxIlQEeXx_9',
    value: 11,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'aL5uT93z_sv',
    value: 12,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'OScCyp44JMg',
    value: 13,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'nrCBmsm5p1P',
    value: 14,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'clubs',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'v26AmWEGF5k',
    value: 2,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'cqN8euZn7q9',
    value: 3,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'Y3bQ1XTSENs',
    value: 4,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 's_Rv_9ntEyw',
    value: 5,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'PwD14mrMmve',
    value: 6,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'LElJy9zw1Ai',
    value: 7,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'BCLDm9YZrXw',
    value: 8,
    name: 'missed',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/mancato_r2oh5w.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'evOmkBVa59q',
    value: 11,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'yszzm6LLDWG',
    value: 12,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'v_mnLl2VOuB',
    value: 13,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'duxuTmkDmhk',
    value: 8,
    name: 'panic',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888950/bang/original/panico_fdczgp.png',
    suit: 'diamond',
    type: 'action',
    needsReaction: false,
    isTargeted: true,
  },
  {
    id: 'tQAl-auZVwB',
    value: 5,
    name: 'saloon',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888951/bang/original/saloon_oubya5.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'olAjWR1wihj',
    value: 8,
    name: 'stagecoach',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/diligenza_wpu1kg.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'kLKn1N1W0Bm',
    value: 9,
    name: 'stagecoach',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888949/bang/original/diligenza_wpu1kg.png',
    suit: 'spades',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
  {
    id: 'UNw-dUpiOWp',
    value: 3,
    name: 'wells fargo',
    imageUrl:
      'https://res.cloudinary.com/trungpham/image/upload/v1602888948/bang/original/wellsfargo_zfpfjj.png',
    suit: 'hearts',
    type: 'action',
    needsReaction: false,
    isTargeted: false,
  },
];
